// <auto-generated />
using System;
using EmployeeAdminPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeAdminPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeAdminPortal.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-b222-c333-d444-e55555555555"),
                            Email = "john.doe@gmail.com",
                            Name = "John Doe",
                            Salary = 45000m
                        },
                        new
                        {
                            Id = new Guid("f1111111-b222-c333-d444-e55555555555"),
                            Email = "alice.smith@gmail.com",
                            Name = "Alice Smith",
                            Salary = 50000m
                        },
                        new
                        {
                            Id = new Guid("c1111111-b222-c333-d444-e55555555555"),
                            Email = "bob.johnson@gmail.com",
                            Name = "Bob Johnson",
                            Salary = 48000m
                        },
                        new
                        {
                            Id = new Guid("d1111111-b222-c333-d444-e55555555555"),
                            Email = "clara.lee@gmail.com",
                            Name = "Clara Lee",
                            Salary = 52000m
                        },
                        new
                        {
                            Id = new Guid("e1111111-b222-c333-d444-e55555555555"),
                            Email = "david.brown@gmail.com",
                            Name = "David Brown",
                            Salary = 47000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
